version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Uncomment and add your Google Analytics ID if needed
      # - NEXT_PUBLIC_GA_MEASUREMENT_ID=G-XXXXXXXXXX
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      timeout: 5s
      interval: 30s
      retries: 3
      start_period: 40s
